language: python
notifications:
  email: false
env:
- DJANGO_VERSION~=1.7.0
- DJANGO_VERSION~=1.8.0
- DJANGO_VERSION~=1.9.0
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -r ci.txt Django==$DJANGO_VERSION
- python setup.py install
script:
- make test
